### ISSUE TITLE
[bug] unknown service saas.api.tenant.v1.TenantService

### ISSUE THREAD

**Issue by alperenakyuzz** [Goxiaoy/go-saas-kit#15]
When I do up with docker, I get this error on login page without making any changes.

**Comment by Goxiaoy** [comment]
Can not reproduce on my side.
service saas.api.tenant.v1.TenantService should be registered 
https://github.com/Goxiaoy/go-saas-kit/blob/12c9287f08ba01b1469b13cd1ca50e12e43fa395/saas/private/server/http.go#L69-L70
Could you please try
```
docker-compose -f docker-compose.yml -f docker-compose.tracing.yml pull
docker-compose -f docker-compose.yml -f docker-compose.tracing.yml up -d
```
Make sure all services started by
```
docker ps
```
If your run up at the first time. you may need to rerun due to the services dependency
```
docker-compose -f docker-compose.yml -f docker-compose.tracing.yml up -d
```
If error still happens , could you please provide more information like screenshots

**Comment by alperenakyuzz** [comment]
It's work. Thanks
